@url = http://localhost:8080
###
GET {{url}}/usuarios
###
GET {{url}}/livros
###
GET {{url}}/emprestimos
###
POST {{url}}/usuarios
Content-Type: application/json

{
    "nome": "Lelouch Lamperouge",
    "email": "britannian.traitor@email.com",
    "telefone": "81777777777",
    "dataCadastro": "2025-04-07"
}
###
POST {{url}}/usuarios
Content-Type: application/json

{
  "nome": "",
  "email": "teste@",
  "telefone": ""
}
###
POST {{url}}/livros
Content-Type: application/json

{
  "titulo": "",
  "autor": "",
  "quantidadeEstoque": -5
}
###
POST {{url}}/emprestimos
Content-Type: application/json

{
  "id_usuario": null,
  "id_livro": null,
  "dataEmprestimo": "2025-04-08",
  "dataDevolucao": "2025-03-01",
  "status": ""
}
###
POST {{url}}/livros
Content-Type: application/json

{
    "titulo": "How to overthrow the government?",
    "autor": "V",
    "quantidadeEstoque": 14 
}
###
POST {{url}}/emprestimos
Content-Type: application/json

{
  "id_usuario": 5,
  "id_livro": 2,
  "dataEmprestimo": "2025-04-06",
  "dataDevolucao": "2025-04-20",
  "status": "emprestado"
}
###
POST {{url}}/emprestimos
Content-Type: application/json

{
  "id_usuario": 1,
  "id_livro": 1,
  "dataEmprestimo": "2025-04-13",
  "dataDevolucao": "2025-04-20",
  "status": "emprestado"
}
